# Android CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-android/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/build_wd
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "midgar/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "midgar/build.gradle" }}
      - run:
          name: Build aar for SDK
          command: ./gradlew :midgar:assembleRelease
      - store_artifacts:
          path: midgar/build/outputs/aar/*.aar
      - run:
         name: Run lint test on sample app to make sure it builds
         command: ./gradlew :app:lintDebug